name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~
            if [ ! -d "Outbound-AI-Frontend" ]; then
              git clone https://github.com/hngprojects/Outbound-AI-Frontend.git
            fi
            cd Outbound-AI-Frontend
            git pull origin main
            npm install
            npm run build
            pm2 restart next-app || pm2 start npm --name "next-app" -- start
            sudo systemctl restart nginx
